"""empty message

Revision ID: 0dfce288b49b
Revises: fe9cd8cd2c53
Create Date: 2020-09-12 23:29:28.355589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dfce288b49b'
down_revision = 'fe9cd8cd2c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'password')
    # ### end Alembic commands ###
