"""empty message

Revision ID: 5147d02ea023
Revises: 0dfce288b49b
Create Date: 2020-09-19 15:15:36.520795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5147d02ea023'
down_revision = '0dfce288b49b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('User', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('User', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
