"""empty message

Revision ID: f24df5b34fb0
Revises: 5147d02ea023
Create Date: 2020-09-19 15:35:05.626938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

revision = 'f24df5b34fb0'
down_revision = '5147d02ea023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum = postgresql.ENUM('normal', 'premium', 'admin',
                                name='userrole')
    role_enum.create(op.get_bind())
    op.add_column('User', sa.Column('role', role_enum, server_default='normal', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'role')
    # ### end Alembic commands ###
